"""Assemble the English manuscript from the translated section files.

WHY THIS EXISTS
    The Chinese paper has `_assemble.py`, which builds MANUSCRIPT.md from the section drafts
    and refuses to write if any cross-reference dangles. The English translation had no
    equivalent, so there was no single English document -- and arXiv submissions need one.

    It is written to REFUSE rather than to produce something partial. The section 9-11 file
    once arrived carrying only two of its three sections with a TRANSLATION-CONTINUES-HERE
    marker, and every check went green because none of them asked whether the English covered
    the Chinese. An assembler that silently emits a 6-of-9-section manuscript would recreate
    exactly that failure at a larger scale, so this one reports what is missing and exits
    non-zero instead.

USAGE
    python paper/en/_assemble.py            # write MANUSCRIPT.md if complete
    python paper/en/_assemble.py --check    # report status, write nothing
"""

from __future__ import annotations

import re
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[2]))
from bench_env import PAPER  # noqa: E402

HERE = PAPER / "en"
OUT = HERE / "MANUSCRIPT.md"

# (file, sections it must contain, human label) -- in manuscript order.
# NOTE: the numbering above is the DRAFT numbering, which collides across files -- two
# different drafts both call themselves section 3. See the results-B/C entry.
SOURCES: list[tuple[str, list[str], str]] = [
    ("00-abstract.md", [], "Abstract"),
    ("01-intro-02.md", ["1", "2"], "Introduction and Related Work"),
    ("03-04-systems-method.md", ["3", "4"], "Systems under test, and Method"),
    ("05-results-A.md", ["5"], "Results A"),
    # DRAFT numbering, not manuscript numbering: these two drafts use section 3 and
    # section 6 internally, colliding with the systems and discussion drafts. The Chinese
    # _assemble.py remaps them (3->6, 6->7, 7->8); carrying the draft numbers here is what
    # lets the same remap apply to the English.
    ("06-07-results-BC.md", ["3", "6"], "Results B and C"),
    # DRAFT numbering again: this draft calls itself section 7 and the assembler remaps
    # 7 -> 8. Fixing only the results-B/C entry left this one wrong, which is what
    # happens when an instance is fixed instead of the table audited.
    ("08-results-D.md", ["7"], "Results D"),
    ("09-10-11-discussion-limits-repro.md", ["9", "10", "11"],
     "Discussion, Limitations, Reproducibility"),
    ("13-ai-disclosure.md", [], "AI-assistance disclosure"),
]


def main() -> int:
    check_only = "--check" in sys.argv
    present: list[tuple[str, str]] = []
    missing: list[str] = []
    incomplete: list[str] = []

    for name, want, label in SOURCES:
        f = HERE / name
        if not f.exists():
            missing.append(f"{label} ({name})")
            continue
        t = f.read_text(encoding="utf-8")
        if "TRANSLATION-CONTINUES-HERE" in t:
            incomplete.append(f"{label} ({name}): carries a CONTINUES marker")
            continue
        have = set(re.findall(r"^#\s*§(\d+)", t, re.M))
        gap = [w for w in want if w not in have]
        if gap:
            incomplete.append(f"{label} ({name}): missing section(s) {gap}")
            continue
        present.append((label, t))

    print(f"English sections available: {len(present)}/{len(SOURCES)}")
    for label, _t in present:
        print(f"  ok      {label}")
    for m in missing:
        print(f"  MISSING {m}")
    for i in incomplete:
        print(f"  PARTIAL {i}")

    if missing or incomplete:
        print()
        print("REFUSING to write MANUSCRIPT.md: the English paper is incomplete.")
        print("A partial manuscript that looks finished is the exact failure this file")
        print("exists to prevent -- see the TRANSLATION-CONTINUES-HERE incident.")
        return 1

    if check_only:
        print("\ncomplete (--check: nothing written)")
        return 0

    # Front matter. WHY this is here and not in a source file: the Chinese
    # manuscript carries its title block at the top of paper/MANUSCRIPT.md, and the
    # English manuscript carried none -- so paper/dist/en.html opened at "# Abstract"
    # and the printed PDF had no title and no author anywhere in 97 pages. The
    # Chinese PDF looked right and the English one did not, which is exactly the kind
    # of one-sided defect that survives inspection because the other language is fine.
    # The title must match the <title> tag p96_render_html.py writes for "en", and
    # match the Zenodo deposit record.
    parts = ["<!-- GENERATED by paper/en/_assemble.py -- edit the section files, not this. -->",
             "",
             "# When a Judgment Layer's Self-Reported Fields Lie",
             "",
             "**Cost, latency and the failure boundary of three judgment layers on the "
             "same items**",
             "",
             "Perry Link",
             "",
             "*Assembled from section sources (`paper/en/_assemble.py`) \u00b7 every figure "
             "carries its n and its artifact*",
             "",
             "> **This paper is measurement and characterisation, not an algorithm paper.**",
             "> Three of its four claims stand independently (cost is not the constraint;",
             "> access-layer self-reported fields are untrustworthy; capability collapse).",
             "> **The fourth \u2014 that a dissimilar judge supplies incremental coverage \u2014 "
             "is not supported in any of the three task regimes**",
             "> (the first two regimes are unmeasurable because the LLM is at ceiling; the",
             "> third lacks power; \u00a78).",
             "",
             "---",
             ""]
    for _label, t in present:
        parts.append(t.rstrip())
        parts.append("\n---\n")

    # the reference list is generated from references.bib, same single source of truth
    # the ENGLISH rendering of the same .bib, so the manuscript is all-English
    refs = HERE / "12-references.md"
    if refs.exists():
        parts.append("# References\n")
        body = refs.read_text(encoding="utf-8")
        # drop the generated file's own front matter; keep the entries
        body = re.sub(r"\A#.*?\n", "", body, count=1, flags=re.S)
        parts.append(body.strip())

    OUT.write_text("\n".join(parts) + "\n", encoding="utf-8")
    text = OUT.read_text(encoding="utf-8")
    print(f"\nwrote {OUT.name}: {len(text)} chars / {text.count(chr(10)) + 1} lines")
    return 0


if __name__ == "__main__":
    sys.exit(main())
