"""Archive published artifacts to results/_superseded/ BEFORE a re-run overwrites them.

Rule honoured (task constraint 3): a script that rewrites an artifact must first preserve
the original under results/_superseded/ with a clear name, and record why in that
directory's README.

Usage:
    python rerun/archive_before_rerun.py P3-clamp-calibration.json [more...]

The suffix is `.pre-rerun`: distinct from the existing `.pre-repair` / `.pre-provenance`
copies, so a reader can tell which forensic layer they are looking at.
"""
from __future__ import annotations

import shutil
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
RESULTS = ROOT / "results"
SUP = RESULTS / "_superseded"
README = SUP / "README.md"

REASON = ("re-measurement (RERUN): the artifact was regenerated by re-running its own "
          "generating script, so the published bytes were preserved first. See "
          "results/RERUN-REPORT.md.")


def main(argv: list[str]) -> int:
    if not argv:
        print("usage: archive_before_rerun.py <artifact.json> [...]")
        return 2
    SUP.mkdir(parents=True, exist_ok=True)
    added = []
    for name in argv:
        src = RESULTS / name
        if not src.exists():
            print(f"  MISSING  {name}")
            continue
        dst = SUP / (name + ".pre-rerun")
        if dst.exists():
            print(f"  already  {name}.pre-rerun")
            continue
        shutil.copy2(src, dst)
        print(f"  copied   {name} -> _superseded/{dst.name}")
        added.append(name)
    if added:
        text = README.read_text(encoding="utf-8")
        if "`.pre-rerun`" not in text:
            text = text.rstrip() + "\n\n" + (
                "## `.pre-rerun` — byte-copies taken before the re-measurement\n\n"
                "Same policy, later layer: taken immediately before the artifact was "
                "regenerated by re-running its own generating script during the "
                "re-measurement. " + REASON + "\n")
        lines = [f"| `{n}.pre-rerun` | byte-copy as published, before the re-run | "
                 f"the re-run itself |" for n in added]
        text = text.rstrip() + "\n" + "\n".join(lines) + "\n"
        README.write_text(text, encoding="utf-8")
        print(f"  README   +{len(added)} row(s)")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
