"""Make the reference-list generator emit an English version alongside the Chinese one.

THE GAP
    `paper/en/_assemble.py` appends `paper/12-references-draft.md`, which is generated from
    `references.bib` and is the single source of truth. But it is generated in CHINESE -- and
    `verify_all.py` I2 warned that the English manuscript therefore contains untranslated
    Chinese.

    The ENTRIES are already language-neutral (author names, titles and venues are English).
    Only the header and the two preamble paragraphs are Chinese. So the right fix is not to
    translate the list but to have the generator emit both renderings from the one .bib,
    which keeps a single source of truth and gives arXiv an all-English document.

    The Chinese preamble is worth keeping rather than dropping: it states the rule that every
    entry was checked against a fetched primary source, and why that rule exists. The English
    version states the same thing.
"""

from __future__ import annotations

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[2]))
from bench_env import PAPER  # noqa: E402

P = ROOT = Path(__file__).resolve().parents[2]
src = P / "src" / "analysis" / "p34_bib_to_markdown.py"
t = src.read_text(encoding="utf-8")

# 1. the output path
t = t.replace(
    'OUT = PAPER / "12-references-draft.md"',
    'OUT = PAPER / "12-references-draft.md"\n'
    '# The English rendering of the SAME .bib. Both are generated, so neither can drift.\n'
    'OUT_EN = PAPER / "en" / "12-references.md"\n'
    'HEADER_EN = """<!-- GENERATED from paper/references.bib by '
    'src/analysis/p34_bib_to_markdown.py.\n'
    '     Edit the .bib, then re-run the script. Do not edit this file. -->\n'
    '\n'
    '# References\n'
    '\n'
    '**This list contains only sources whose original was checked.** Every entry\\'s title,\n'
    'authors, year and venue is taken from a **fetched primary source** (the arXiv entries were\n'
    'verified in one pass against `export.arxiv.org/api/query`), never from memory.\n'
    '\n'
    '> **Why this rule is stated before the list**: arXiv\\'s penalty for a submission with\n'
    '> "incontrovertible evidence that the authors did not check the results of LLM generation"\n'
    '> is a **one-year ban**, and the first example it names is **hallucinated references**. This\n'
    '> project\\'s source tiers (`recon/R2-verified-externals.md`) already forbid third-party\n'
    '> relay as evidence; the reference list is held to the same standard.\n'
    '"""', 1)

# 2. build() takes a language
t = t.replace(
    'def build() -> str:\n'
    '    entries = parse_bib(BIB.read_text(encoding="utf-8"))\n'
    '    entries.sort(key=lambda e: (e.get("author", "").split(",")[0].lower(),\n'
    '                                e.get("year", "")))\n'
    '    lines = [HEADER, ""]',
    'def build(lang: str = "zh") -> str:\n'
    '    entries = parse_bib(BIB.read_text(encoding="utf-8"))\n'
    '    entries.sort(key=lambda e: (e.get("author", "").split(",")[0].lower(),\n'
    '                                e.get("year", "")))\n'
    '    lines = [HEADER_EN if lang == "en" else HEADER, ""]', 1)

t = t.replace(
    '    lines.append("**引用键索引**（正文以 `[@key]` 引用，本表由脚本从 `.bib` 生成）：")',
    '    lines.append("**Key index** (the text cites as `[@key]`; this table is generated from '
    'the `.bib`):" if lang == "en"\n'
    '                 else "**引用键索引**（正文以 `[@key]` 引用，本表由脚本从 `.bib` 生成）：")', 1)

# 3. main() writes and checks both
t = t.replace(
    'def main() -> int:\n'
    '    rendered = build()\n'
    '    if "--check" in sys.argv:\n'
    '        current = OUT.read_text(encoding="utf-8") if OUT.exists() else ""\n'
    '        if current != rendered:\n'
    '            print("STALE: 12-references-draft.md differs from references.bib")\n'
    '            print("       re-run without --check to regenerate")\n'
    '            return 1\n'
    '        print(f"fresh: {len(parse_bib(BIB.read_text(encoding=\'utf-8\')))} entries")\n'
    '        return 0\n'
    '    OUT.write_text(rendered, encoding="utf-8")\n'
    '    n = len(parse_bib(BIB.read_text(encoding="utf-8")))\n'
    '    print(f"wrote {OUT.name}: {n} verified references")\n'
    '    return 0',
    'def main() -> int:\n'
    '    pairs = [(OUT, build("zh")), (OUT_EN, build("en"))]\n'
    '    if "--check" in sys.argv:\n'
    '        stale = []\n'
    '        for path, rendered in pairs:\n'
    '            current = path.read_text(encoding="utf-8") if path.exists() else ""\n'
    '            if current != rendered:\n'
    '                stale.append(path.name)\n'
    '        if stale:\n'
    '            print(f"STALE: {\', \'.join(stale)} differ(s) from references.bib")\n'
    '            print("       re-run without --check to regenerate")\n'
    '            return 1\n'
    '        print(f"fresh: {len(parse_bib(BIB.read_text(encoding=\'utf-8\')))} entries, '
    'both languages")\n'
    '        return 0\n'
    '    for path, rendered in pairs:\n'
    '        path.parent.mkdir(parents=True, exist_ok=True)\n'
    '        path.write_text(rendered, encoding="utf-8")\n'
    '    n = len(parse_bib(BIB.read_text(encoding="utf-8")))\n'
    '    print(f"wrote {OUT.name} and en/{OUT_EN.name}: {n} verified references each")\n'
    '    return 0', 1)

src.write_text(t, encoding="utf-8")
print("  ok    p34 now emits both languages")

# 4. the English assembler should append the ENGLISH list
a = PAPER / "en" / "_assemble.py"
at = a.read_text(encoding="utf-8")
if '"12-references.md"' not in at:
    at = at.replace(
        'refs = PAPER / "12-references-draft.md"',
        '# the ENGLISH rendering of the same .bib, so the manuscript is all-English\n'
        '    refs = HERE / "12-references.md"', 1)
    a.write_text(at, encoding="utf-8")
    print("  ok    English assembler now appends the English list")
else:
    print("  ok    English assembler already correct")
